-- ** Database generated with pgModeler (PostgreSQL Database Modeler).
-- ** pgModeler version: 1.2.0
-- ** PostgreSQL version: 16.0
-- ** Project Site: pgmodeler.io
-- ** Model Author: ---

-- ** Database creation must be performed outside a multi lined SQL file. 
-- ** These commands were put in this file only as a convenience.

-- object: new_database | type: DATABASE --

SET search_path TO pg_catalog,public;
-- ddl-end --

-- object: public.fato_cvli | type: TABLE --
-- DROP TABLE IF EXISTS public.fato_cvli CASCADE;
CREATE TABLE public.fato_cvli (
	tempo integer NOT NULL,
	municipio integer NOT NULL,
	subjetividade integer NOT NULL,
	ambiente integer NOT NULL,
	instrumento integer NOT NULL,
	faixa_etaria integer NOT NULL,
	raca_cor integer NOT NULL,
	sexo integer NOT NULL,
	total_cvli integer,
	CONSTRAINT fato_cvli_pk PRIMARY KEY (tempo,municipio,subjetividade,ambiente,instrumento,faixa_etaria,raca_cor,sexo)
);
-- ddl-end --
ALTER TABLE public.fato_cvli OWNER TO postgres;
-- ddl-end --

-- object: public.dim_tempo | type: TABLE --
-- DROP TABLE IF EXISTS public.dim_tempo CASCADE;
CREATE TABLE public.dim_tempo (
	pk_tempo integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	data date NOT NULL,
	ano integer NOT NULL,
	mes_num integer NOT NULL,
	mes_nome varchar(20) NOT NULL,
	mes_ano varchar(7) NOT NULL,
	dia integer NOT NULL,
	CONSTRAINT dim_tempo_pk PRIMARY KEY (pk_tempo)
);
-- ddl-end --
ALTER TABLE public.dim_tempo OWNER TO postgres;
-- ddl-end --

-- object: public.dim_municipio | type: TABLE --
-- DROP TABLE IF EXISTS public.dim_municipio CASCADE;
CREATE TABLE public.dim_municipio (
	pk_municipio integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	municipio varchar(255) NOT NULL,
	CONSTRAINT dim_municipio_pk PRIMARY KEY (pk_municipio)
);
-- ddl-end --
ALTER TABLE public.dim_municipio OWNER TO postgres;
-- ddl-end --

-- object: public.dim_faixa_etaria | type: TABLE --
-- DROP TABLE IF EXISTS public.dim_faixa_etaria CASCADE;
CREATE TABLE public.dim_faixa_etaria (
	pk_faixa_etaria integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	faixa_etaria varchar(10) NOT NULL,
	CONSTRAINT dim_faixa_etaria_pk PRIMARY KEY (pk_faixa_etaria)
);
-- ddl-end --
ALTER TABLE public.dim_faixa_etaria OWNER TO postgres;
-- ddl-end --

-- object: public.dim_bairro | type: TABLE --
-- DROP TABLE IF EXISTS public.dim_bairro CASCADE;
CREATE TABLE public.dim_bairro (
	pk_bairro integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	bairro varchar(255) NOT NULL,
	CONSTRAINT dim_bairro_pk PRIMARY KEY (pk_bairro)
);
-- ddl-end --
ALTER TABLE public.dim_bairro OWNER TO postgres;
-- ddl-end --

-- object: public.dim_bairro_municipio | type: TABLE --
-- DROP TABLE IF EXISTS public.dim_bairro_municipio CASCADE;
CREATE TABLE public.dim_bairro_municipio (
	municipio integer NOT NULL,
	bairro integer NOT NULL,
	CONSTRAINT dim_bairro_municipio_pk PRIMARY KEY (municipio,bairro)
);
-- ddl-end --
ALTER TABLE public.dim_bairro_municipio OWNER TO postgres;
-- ddl-end --

-- object: public.dim_ibge | type: TABLE --
-- DROP TABLE IF EXISTS public.dim_ibge CASCADE;
CREATE TABLE public.dim_ibge (
	pk_ibge integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	fk_municipio integer NOT NULL,
	ano integer NOT NULL,
	populacao integer NOT NULL,
	CONSTRAINT dim_ibge_pk PRIMARY KEY (pk_ibge)
);
-- ddl-end --
ALTER TABLE public.dim_ibge OWNER TO postgres;
-- ddl-end --

-- object: public.dim_subjetividade | type: TABLE --
-- DROP TABLE IF EXISTS public.dim_subjetividade CASCADE;
CREATE TABLE public.dim_subjetividade (
	pk_subjetividade integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	subjetividade varchar(255) NOT NULL,
	CONSTRAINT dim_subjetividade_pk PRIMARY KEY (pk_subjetividade)
);
-- ddl-end --
ALTER TABLE public.dim_subjetividade OWNER TO postgres;
-- ddl-end --

-- object: public.dim_raca_cor | type: TABLE --
-- DROP TABLE IF EXISTS public.dim_raca_cor CASCADE;
CREATE TABLE public.dim_raca_cor (
	pk_raca_cor integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	raca_cor varchar(20) NOT NULL,
	CONSTRAINT dim_raca_cor_pk PRIMARY KEY (pk_raca_cor)
);
-- ddl-end --
ALTER TABLE public.dim_raca_cor OWNER TO postgres;
-- ddl-end --

-- object: public.dim_ambiente | type: TABLE --
-- DROP TABLE IF EXISTS public.dim_ambiente CASCADE;
CREATE TABLE public.dim_ambiente (
	pk_ambiente integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	ambiente varchar(255) NOT NULL,
	CONSTRAINT dim_ambiente_pk PRIMARY KEY (pk_ambiente)
);
-- ddl-end --
ALTER TABLE public.dim_ambiente OWNER TO postgres;
-- ddl-end --

-- object: public.dim_instrumento | type: TABLE --
-- DROP TABLE IF EXISTS public.dim_instrumento CASCADE;
CREATE TABLE public.dim_instrumento (
	pk_instrumento integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	instrumento varchar(255) NOT NULL,
	CONSTRAINT dim_instrumento_pk PRIMARY KEY (pk_instrumento)
);
-- ddl-end --
ALTER TABLE public.dim_instrumento OWNER TO postgres;
-- ddl-end --

-- object: public.dim_sexo | type: TABLE --
-- DROP TABLE IF EXISTS public.dim_sexo CASCADE;
CREATE TABLE public.dim_sexo (
	pk_sexo integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	sexo varchar(15) NOT NULL,
	CONSTRAINT dim_sexo_pk PRIMARY KEY (pk_sexo)
);
-- ddl-end --
ALTER TABLE public.dim_sexo OWNER TO postgres;
-- ddl-end --

-- object: fk_dim_tempo | type: CONSTRAINT --
-- ALTER TABLE public.fato_cvli DROP CONSTRAINT IF EXISTS fk_dim_tempo CASCADE;
ALTER TABLE public.fato_cvli ADD CONSTRAINT fk_dim_tempo FOREIGN KEY (tempo)
REFERENCES public.dim_tempo (pk_tempo) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_dim_municipio | type: CONSTRAINT --
-- ALTER TABLE public.fato_cvli DROP CONSTRAINT IF EXISTS fk_dim_municipio CASCADE;
ALTER TABLE public.fato_cvli ADD CONSTRAINT fk_dim_municipio FOREIGN KEY (municipio)
REFERENCES public.dim_municipio (pk_municipio) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_dim_subjetividade | type: CONSTRAINT --
-- ALTER TABLE public.fato_cvli DROP CONSTRAINT IF EXISTS fk_dim_subjetividade CASCADE;
ALTER TABLE public.fato_cvli ADD CONSTRAINT fk_dim_subjetividade FOREIGN KEY (subjetividade)
REFERENCES public.dim_subjetividade (pk_subjetividade) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_dim_ambiente | type: CONSTRAINT --
-- ALTER TABLE public.fato_cvli DROP CONSTRAINT IF EXISTS fk_dim_ambiente CASCADE;
ALTER TABLE public.fato_cvli ADD CONSTRAINT fk_dim_ambiente FOREIGN KEY (ambiente)
REFERENCES public.dim_ambiente (pk_ambiente) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_dim_instrumento | type: CONSTRAINT --
-- ALTER TABLE public.fato_cvli DROP CONSTRAINT IF EXISTS fk_dim_instrumento CASCADE;
ALTER TABLE public.fato_cvli ADD CONSTRAINT fk_dim_instrumento FOREIGN KEY (instrumento)
REFERENCES public.dim_instrumento (pk_instrumento) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_dim_faixa_etaria | type: CONSTRAINT --
-- ALTER TABLE public.fato_cvli DROP CONSTRAINT IF EXISTS fk_dim_faixa_etaria CASCADE;
ALTER TABLE public.fato_cvli ADD CONSTRAINT fk_dim_faixa_etaria FOREIGN KEY (faixa_etaria)
REFERENCES public.dim_faixa_etaria (pk_faixa_etaria) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_dim_raca_cor | type: CONSTRAINT --
-- ALTER TABLE public.fato_cvli DROP CONSTRAINT IF EXISTS fk_dim_raca_cor CASCADE;
ALTER TABLE public.fato_cvli ADD CONSTRAINT fk_dim_raca_cor FOREIGN KEY (raca_cor)
REFERENCES public.dim_raca_cor (pk_raca_cor) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_dim_sexo | type: CONSTRAINT --
-- ALTER TABLE public.fato_cvli DROP CONSTRAINT IF EXISTS fk_dim_sexo CASCADE;
ALTER TABLE public.fato_cvli ADD CONSTRAINT fk_dim_sexo FOREIGN KEY (sexo)
REFERENCES public.dim_sexo (pk_sexo) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_dim_municipio | type: CONSTRAINT --
-- ALTER TABLE public.dim_bairro_municipio DROP CONSTRAINT IF EXISTS fk_dim_municipio CASCADE;
ALTER TABLE public.dim_bairro_municipio ADD CONSTRAINT fk_dim_municipio FOREIGN KEY (municipio)
REFERENCES public.dim_municipio (pk_municipio) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_dim_bairro | type: CONSTRAINT --
-- ALTER TABLE public.dim_bairro_municipio DROP CONSTRAINT IF EXISTS fk_dim_bairro CASCADE;
ALTER TABLE public.dim_bairro_municipio ADD CONSTRAINT fk_dim_bairro FOREIGN KEY (bairro)
REFERENCES public.dim_bairro (pk_bairro) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_dim_municipio | type: CONSTRAINT --
-- ALTER TABLE public.dim_ibge DROP CONSTRAINT IF EXISTS fk_dim_municipio CASCADE;
ALTER TABLE public.dim_ibge ADD CONSTRAINT fk_dim_municipio FOREIGN KEY (fk_municipio)
REFERENCES public.dim_municipio (pk_municipio) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
-- ddl-end --


