CREATE TABLE public.fato_cvli (
	pk_fato integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	bairro_municipio integer NOT NULL,
	tempo integer NOT NULL,
	subjetividade integer NOT NULL,
	ambiente integer NOT NULL,
	instrumento integer NOT NULL,
	faixa_etaria integer NOT NULL,
	raca_cor integer NOT NULL,
	sexo integer NOT NULL,
	total_cvli integer NOT NULL,
	CONSTRAINT fato_cvli_pk PRIMARY KEY (pk_fato)
);

CREATE TABLE public.dim_tempo (
	pk_tempo integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	data date NOT NULL,
	ano integer NOT NULL,
	mes_num integer NOT NULL,
	mes_nome varchar(20) NOT NULL,
	mes_ano varchar(7) NOT NULL,
	dia integer NOT NULL,
	CONSTRAINT dim_tempo_pk PRIMARY KEY (pk_tempo)
);

CREATE TABLE public.dim_bairro_municipio (
	pk_bairro_municipio integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	fk_bairro integer NOT NULL,
	fk_municipio integer NOT NULL,
	CONSTRAINT pk_dim_bairro_municipio PRIMARY KEY (pk_bairro_municipio)
);

CREATE TABLE public.dim_faixa_etaria (
	pk_faixa_etaria integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	faixa_etaria varchar(10) NOT NULL,
	CONSTRAINT dim_faixa_etaria_pk PRIMARY KEY (pk_faixa_etaria)
);

CREATE TABLE public.dim_ibge (
	pk_ibge integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	fk_municipio integer NOT NULL,
	ano integer NOT NULL,
	populacao integer NOT NULL,
	CONSTRAINT dim_ibge_pk PRIMARY KEY (pk_ibge)
);

CREATE TABLE public.dim_subjetividade (
	pk_subjetividade integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	subjetividade varchar(255) NOT NULL,
	CONSTRAINT dim_subjetividade_pk PRIMARY KEY (pk_subjetividade)
);

CREATE TABLE public.dim_raca_cor (
	pk_raca_cor integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	raca_cor varchar(20) NOT NULL,
	CONSTRAINT dim_raca_cor_pk PRIMARY KEY (pk_raca_cor)
);

CREATE TABLE public.dim_ambiente (
	pk_ambiente integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	ambiente varchar(255) NOT NULL,
	CONSTRAINT dim_ambiente_pk PRIMARY KEY (pk_ambiente)
);

CREATE TABLE public.dim_instrumento (
	pk_instrumento integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	instrumento varchar(255) NOT NULL,
	CONSTRAINT dim_instrumento_pk PRIMARY KEY (pk_instrumento)
);

CREATE TABLE public.dim_sexo (
	pk_sexo integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	sexo varchar(15) NOT NULL,
	CONSTRAINT dim_sexo_pk PRIMARY KEY (pk_sexo)
);

CREATE TABLE public.dim_municipio (
	pk_municipio integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	municipio varchar(255) NOT NULL,
	CONSTRAINT dim_municipio_pk PRIMARY KEY (pk_municipio)
);

CREATE TABLE public.dim_bairro (
	pk_bairro integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	bairro varchar(100) NOT NULL,
	CONSTRAINT dim_bairro_pk PRIMARY KEY (pk_bairro)
);

ALTER TABLE public.fato_cvli ADD CONSTRAINT fk_dim_tempo FOREIGN KEY (tempo)
REFERENCES public.dim_tempo (pk_tempo) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE public.fato_cvli ADD CONSTRAINT fk_dim_subjetividade FOREIGN KEY (subjetividade)
REFERENCES public.dim_subjetividade (pk_subjetividade) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE public.fato_cvli ADD CONSTRAINT fk_dim_ambiente FOREIGN KEY (ambiente)
REFERENCES public.dim_ambiente (pk_ambiente) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE public.fato_cvli ADD CONSTRAINT fk_dim_instrumento FOREIGN KEY (instrumento)
REFERENCES public.dim_instrumento (pk_instrumento) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE public.fato_cvli ADD CONSTRAINT fk_dim_faixa_etaria FOREIGN KEY (faixa_etaria)
REFERENCES public.dim_faixa_etaria (pk_faixa_etaria) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE public.fato_cvli ADD CONSTRAINT fk_dim_raca_cor FOREIGN KEY (raca_cor)
REFERENCES public.dim_raca_cor (pk_raca_cor) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE public.fato_cvli ADD CONSTRAINT fk_dim_sexo FOREIGN KEY (sexo)
REFERENCES public.dim_sexo (pk_sexo) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE public.fato_cvli ADD CONSTRAINT fk_dim_bairro_municipio FOREIGN KEY (bairro_municipio)
REFERENCES public.dim_bairro_municipio (pk_bairro_municipio) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE public.dim_bairro_municipio ADD CONSTRAINT fk_dim_municipio FOREIGN KEY (fk_municipio)
REFERENCES public.dim_municipio (pk_municipio) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE public.dim_bairro_municipio ADD CONSTRAINT fk_dim_bairro FOREIGN KEY (fk_bairro)
REFERENCES public.dim_bairro (pk_bairro) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE public.dim_ibge ADD CONSTRAINT fk_dim_municipio FOREIGN KEY (fk_municipio)
REFERENCES public.dim_municipio (pk_municipio) MATCH SIMPLE
ON DELETE NO ACTION ON UPDATE NO ACTION;
